name: Generate docs and coverage report

on:
  push:
    branches:
      - main

jobs:
  coverage-report:
    name: Coverage report
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/docs-and-coverage.yml@v1
    with:
      prepare-gh-pages-commands: |
        mv docs/* ./gh-pages
        mv coverage/lcov-report ./gh-pages/coverage
