name: E2E Tests
on:
  # TODO Remove
  pull_request:
  workflow_dispatch:
jobs:
  read-version:
    name: 'Read package version'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Read version from package.json
        id: version
        run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT
  e2e-tests:
    name: 'Run E2E tests'
    needs: read-version
    uses: fingerprintjs/dx-team-orchestra/.github/workflows/server-sdk-e2e-tests.yml@ci/release-e2e-tests-status-report
    with:
      run-node-sdk-tests: true
      sdk-version: ${{ needs.read-version.outputs.version }}
      is-workflow-call: true
