name: Release
on:
  push:
    branches:
      - main
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install Node packages
        run: yarn install --ignore-engines

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          HUSKY: 0
